### ISSUE TITLE
make Google Forms

### ISSUE THREAD

**Issue by oshimaryo** [webdino/gitfab2#1155]
- 技術的な問い合わせ
- その他一般的な問い合わせ
  等の問い合わせで、メールだと送信者の手間が多い/一覧しにくい/振り分けにくい/ステータスがわからないので。
  http://katahirado.hatenablog.com/entry/2014/04/25/012222

SPAMも減る

**Comment by ToruHagihara** [comment]
ひとつ質問です。
fabbleの機能要望やUX改善案などの問い合わせをIssuesに直接作成しても良いものでしょうか？
Issuesに作成される前のステップで一覧管理されているなら運用が混乱しそうなので、上記の問い合わせフォームを利用したいと思っています。

**Comment by oshimaryo** [comment]
@ToruHagihara 
ぜひ、Issueを作ってください！
現状、Issuesでのみ管理しています。
上記問い合わせフォームについては、いままでのメールのコンタクトの代替や、GitHubでIssueを作ることにハードルを感じる人向けの用途を想定しています。

**Comment by ToruHagihara** [comment]
ありがとうございます、IssueのラベルでFeature Reqest 的なものがなかったので躊躇していました！
アイデアが出たら載せていきます！

よく考えると「Fabbleユーザー=必ずGitHubアカウントを持っている」 なので、上手くするとさらに手間が省ける仕組みができるかもですね。

**Comment by oshimaryo** [comment]
よろしくお願いします！
'feature request'のラベルを追加しておきましたー
