### ISSUE TITLE
[Disucussion Needed] Buy Materials Button 

### ISSUE THREAD

**Issue by oshimaryo** [webdino/gitfab2#965]
秋月・ツクモ等おそらく頻出するオンラインショップで、材料を全てをショッピングカートに入れるボタン

**Comment by ToruHagihara** [comment]
この種類の素材情報を共有する機能がとても欲しいです。
素材がどういう場所で手に入るかが分かるだけでも十分ありがたいです。
現状、その分野の初学者にとっては、材料入手までの手がかりを見つけるところが難しいのが正直な感想です。

自分のProjectではMaterialの参照URLを秋月のページを指定したりしましたが、他プロジェクトとの連携はなく、イマイチ活かせていません。また、商品そのものを書くと生産中止になったりするため、どの程度の情報を書いておくのが良いか悩ましいところです。

#1143 とも絡んでくる内容かと思いますが、欲しい機能に名前をつけるとしたら以下のような感じでしょうか。
・素材をキーにしたプロジェクト内検索
・素材をキーにしたプロジェクト横断検索
・素材をキーにしたサイト外検索
